### ISSUE TITLE
Add mutex for getting frame

### ISSUE THREAD

**Issue by guanming001** [Liang-Hsuan/Hand-Detection#8]
Hi 

This is a nicely done code, but I think you may have missed out on adding mutex for getting frame, 
For example in hand_detection.h:

    Mat getFrame() {
	Mat frame;
	mtx.lock();
	frame = currentFrame;
	mtx.unlock();
        return frame;
    }

**Comment by leonma333** [comment]
@guanming001 thanks for opening an issue, I think you might be right about this. The reason I didn't place mutex around `getFrame()` function is because of the `currentFrame` private variable assignment is already inside the mutex (see the snippet below), so I thought it would be fine reading it without locking it. Now I think about this maybe adding mutex is necessary since there is no guarantee that in the middle of reading from `currentFrame` it will not be changed in the `start()` thread.

https://github.com/Liang-Hsuan/Hand-Detection/blob/86e759bfe23b50f474c553a8230d7dddeadf792a/hand_detection.h#L57-L61

I think the following will fix the problem:

``` C++
Mat getFrame() {
Mat frame;
mtx.lock();
frame = currentFrame.clone(); // Note: use clone here since frame = currentFrame will return pointer?
mtx.unlock();
    return frame;
}
```
